### ISSUE TITLE
Generating database fails

### ISSUE THREAD

**Issue by sniperle** [n76/lacells-creator#17]
Because actually the LocalGsmNlpBackend 0.9.1 (µgUnifiedNlp without GApps) fails to generate the database (for me), I tried using this script to generate one instead.

While generating I'm getting this happens:
./lacells-creator -i -c262,520 -m 
Importing mozilla cell data
./towers_mozilla.csv:8319154: INSERT failed: database or disk is full
Importing opencellid cell data
./towers_opencellid.csv:4441184: INSERT failed: database or disk is full
Error: near line 52: database or disk is full
Error: near line 53: database or disk is full
Filtering rows
Merging cell towers
Error: near line 69: database or disk is full

What can I do to solve this problem ?
And is it a known problem that the LocalGsmNlpBackend (0.9.1) is actually unable to create a database file ?

Thanks :-)

**Comment by n76** [comment]
Do fix your off-line database generation you need to fix the cause of the "database or disk is full" message. Do you have more storage available to you?

I typically use the in-app based database generation. It does have an issue that it will not continue to download and build the database if it looses focus on the screen and it take a while to run. But since I only update the database about once a month it is not a big deal to simply set the phone aside and let it run for as long as it needs.

**Comment by sniperle** [comment]
The storage is not the problem, I have plenty of space on my harddisk. Any other idea to mention ?

And the in-app database generation is working like on older versions of the plugin. But after finishing (without error) there is only a file with 20kb generated which is pretty unusable. Any mentions here? I can provide the log if you want.

**Comment by n76** [comment]
A log would be good. :)

**Comment by sniperle** [comment]
OK first the generation on my phone, here the lacells_gen.log
MCC filter: 262,520
No MNC Filters, assume world
Getting Tower Data From Open Cell ID. . .
URL is http://opencellid.org/downloads/?apiKey=dev-usr--a48b-4174-b2ef-48818e1d0dc2&filename=cell_towers.csv.gz
Content length = 184278829
Records Read: 7833102, Inserted: 1240074
Total Time: 596649ms (0.076ms/record)
Getting Tower Data From Mozilla Location Services. . .
URL is https://d17pt8qph6ncyq.cloudfront.net/export/MLS-full-cell-export-2015-08-02T000000.csv.gz
Content length = 332376069
Records Read: 12688427, Inserted: 1020790
Total Time: 864879ms (0.068ms/record)
Creating indicies for faster access.
Total Time: 1461614ms
Finished.

According to the log file and the first screenshots, everything seems OK. 
But as you can see on the second screenshot the newly created database is has only 20kb size.
![screenshot_2015-08-02-17-47-31](https://cloud.githubusercontent.com/assets/3104188/9026892/31936462-3940-11e5-9949-1ddd270e4528.png)
![screenshot_2015-08-02-17-48-02](https://cloud.githubusercontent.com/assets/3104188/9026893/381f4904-3940-11e5-8c58-917248d740c4.png)

**Comment by n76** [comment]
Interesting. . . I've just duplicated the issue on my own phone.

**Comment by BridouZ** [comment]
I can confirm I have the issue too

**Comment by BridouZ** [comment]
Can We have an apk for 0.9.2 ?

**Comment by n76** [comment]
F-Droid should have a new build shortly (I assume that is where you got yours). In the meantime my copy is now at https://dl.dropboxusercontent.com/u/19663978/Local-GSM-Backend_0_9_2.apk 

My signature is different so you cannot upgrade to mine nor upgrade away: You will have to remove your existing and then do an install.

I will remove my copy from Dropbox when I see F-Droid has my latest.

**Comment by sgelb** [comment]
Using the bash script, I ran into the same problem as @sniperle. Here is my workaround, may it help others:

Sqlite stores temporary data somewhere on /, which is rather small in my case. As I have enough RAM, I added [```PRAGMA temp_store = 2;```](https://www.sqlite.org/pragma.html#pragma_temp_store) to the other PRAGMA lines in [process()](https://github.com/n76/lacells-creator/blob/master/lib/process#L187) in lib/process. This way, sqlite stores temporary data in memory only. Another way is [```PRAGMA temp_store_directory```](https://www.sqlite.org/pragma.html#pragma_temp_store_directory), but this is deprecated.
