### ISSUE TITLE
Alternative script for lacells.db creation

### ISSUE THREAD

**Issue by sobrus** [n76/lacells-creator#18]
Hi, 

It's not really an issue, but I would like to contribute my script for lacells.db creation.
It does more-or-less the same thing as lacells-creator does, albeit MUCH faster.

It is simple and has no advanced functionality, but should be enough for most users who only need to create databases.

You can find it here
https://github.com/sobrus/FastLacellsGenerator

**Comment by n76** [comment]
Looks reasonable. I'll update my page to link to yours.
