### ISSUE TITLE
Error "rm: cannot remove ‘lacells.db’: No such file or directory"

### ISSUE THREAD

**Issue by squatch04** [n76/lacells-creator#19]
Ran the script and got this error, is this normal? It did generate a .db file in the directory though (less than 1MB in size).

Full output:
Downloading data
rm: cannot remove ‘lacells.db’: No such file or directory
Generating database
off

**Comment by IzzySoft** [comment]
Looks normal to me for a first run: it downloads the data, then tries to remove the database from a previous run (which doesn't exist if there was no previous run, or if you deleted that file yourself), and finally generates the database.

What indeed *does* look a bit suspicious is the generated database being that small. But it's hard to say anything about that without knowing your configuration.

**Comment by squatch04** [comment]
Without looking at the code in the script, what seemed a little off putting to me was the file size and the fact that i was expecting the output to display something like "generating database....".
I am from from the Caribbean (small island) so that's most likely the reason for the file size being so small.
It was my first run of the script so that explains the 'cannot remove lacells.db' error.
Is there any way to confirm that the database was generated successfully?

**Comment by n76** [comment]
You should have sqlite3 installed on your computer if you were able to run the script. If so, then open the database with it and do something like:

```
sqlite> .schema
CREATE TABLE cells(mcc INTEGER, mnc INTEGER, lac INTEGER, cid INTEGER, longitude REAL, latitude REAL, accuracy REAL, samples INTEGER, altitude REAL);
CREATE INDEX _idx1 ON cells (mcc, mnc, lac, cid);
CREATE INDEX _idx2 ON cells (lac, cid);
sqlite> select * from cells limit 10;
310|0|31332|16767489|-86.6596|34.966857|500.0|1|-1.0
310|0|42984|7931457|-122.3576907|48.7219022|881.0|3|-1.0
310|0|42984|7931459|-122.3697|48.726215|500.0|1|-1.0
310|4|2510|16463771|46.3674271|38.0420427|5287.0|123|-1.0
310|4|12620|59070571|-80.19179|25.76168|500.0|1|-1.0
310|4|21070|201247027|-106.359744|31.656153|500.0|1|-1.0
310|4|21070|201247732|-106.374448|31.696347|500.0|3|-1.0
310|4|22527|190234556|51.632852|36.589601|500.0|1|-1.0
310|4|29010|190122999|51.336613|35.786197|500.0|1|-1.0
310|4|29010|190169547|51.482695|35.788516|500.0|1|-1.0
sqlite> .quit
```

(Show the tables (actually only one table) and the fields in it, then dump the first 10 records in the table. The above is from a database created on my phone but the results should look much the same as for a database created on your PC.)

**Comment by squatch04** [comment]
This is my output:

`sqlite> .schema
CREATE TABLE cells (mcc INTEGER,mnc INTEGER,lac INTEGER,cid INTEGER,longitude REAL,latitude REAL,altitude REAL,accuracy REAL,samples INTEGER);
CREATE INDEX _idx1 ON cells (mcc, mnc, lac, cid);
CREATE INDEX _idx2 ON cells (lac, cid);
sqlite> select * from cells limit 10;
374|12|101|30621|-61.507489|10.670389|-1.0|500.0|96
374|12|101|30623|-61.508983|10.669868|-1.0|500.0|51
374|12|101|32361|-61.508525|10.658569|-1.0|500.0|20
374|12|101|32443|-61.512808|10.656785|-1.0|500.0|1
374|12|101|32451|-61.508408|10.658779|-1.0|500.0|2
374|12|101|32452|-61.508705|10.656713|-1.0|500.0|23
374|12|101|32453|-61.51126|10.656287|-1.0|500.0|70
374|12|101|32613|-61.508661|10.660931|-1.0|500.0|12
374|12|101|32681|-61.510818|10.664335|-1.0|500.0|2
374|12|101|32682|-61.509223|10.661249|-1.0|500.0|38
sqlite> `

So all is well and good! Thanks to IzzySoft and n76 for your assistance.
